[package]
name = "hello_macro_derive"
version = "0.1.0"
authors = ["torresashjian <migueltorreslopez@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6.3"
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
