[package]
name = "my_simple_app"
version = "0.1.0"
authors = ["Miguel Torres <migueltorreslopez@gmail.com>"]

[dependencies]
my_simple_trigger = { path = "../my_simple_trigger" }
#data = { path = "../core_runtime/data" }
