[package]
name = "my_simple_trigger"
version = "0.0.1"
authors = [ "user <myemail@email.com>" ]
edition = "2018"


[dependencies]
#dovetail_derive = { path = "../dovetail_derive" }
#data = { path = "../core_runtime/data" }
my_simple_flow = { path = "../my_simple_flow" }
