[package]
name = "dovetail_core"
version = "0.1.0"
authors = ["torresashjian <migueltorreslopez@gmail.com>"]
edition = "2018"

[dependencies]
syn = "0.15"
serde_derive = "1.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
quote = "0.6.3"
proc-macro2 = "0.4.27"
